import datetime
import logging
from typing import Dict, Any

logger = logging.getLogger(__name__)


def generate_pdf_report(
    report_data: Dict[str, Any],
    recruitment_info: Dict[str, Any],
    version: str = "1.0",
) -> bytes:
    """Generates a professional multi-page PDF report from report_data using WeasyPrint (with fallback)."""
    today_str = datetime.date.today().strftime("%d %B %Y")
    exam_title = recruitment_info.get("name", "Government Exam Research Report")
    org = recruitment_info.get("org", "Government Board")
    advt = recruitment_info.get("advt_number", "Official Notification")

    default_fallback = "Information could not be reliably determined from the available sources."

    html_content = f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{exam_title} - Verification Report</title>
    <style>
        @page {{
            size: A4;
            margin: 20mm 15mm 20mm 15mm;
            @bottom-right {{
                content: "Page " counter(page) " of " counter(pages);
                font-family: 'Helvetica', 'Arial', sans-serif;
                font-size: 8pt;
                color: #666;
            }}
            @bottom-left {{
                content: "GovLens AI Report v{version} | Generated {today_str}";
                font-family: 'Helvetica', 'Arial', sans-serif;
                font-size: 8pt;
                color: #666;
            }}
        }}
        body {{
            font-family: 'Helvetica', 'Arial', sans-serif;
            color: #1e293b;
            line-height: 1.5;
            font-size: 10pt;
        }}
        .header {{
            border-bottom: 2px solid #2563eb;
            padding-bottom: 12px;
            margin-bottom: 20px;
        }}
        .title {{
            font-size: 20pt;
            font-weight: bold;
            color: #1e3a8a;
            margin: 0;
        }}
        .subtitle {{
            font-size: 11pt;
            color: #475569;
            margin-top: 4px;
        }}
        .disclaimer {{
            background-color: #fef2f2;
            border-left: 4px solid #ef4444;
            padding: 10px;
            margin-bottom: 20px;
            font-size: 8.5pt;
            color: #991b1b;
        }}
        h2 {{
            font-size: 13pt;
            color: #1e3a8a;
            border-bottom: 1px solid #cbd5e1;
            padding-bottom: 4px;
            margin-top: 18px;
            margin-bottom: 8px;
        }}
        table {{
            width: 100%;
            border-collapse: collapse;
            margin-top: 8px;
            margin-bottom: 14px;
            font-size: 9pt;
        }}
        th, td {{
            border: 1px solid #cbd5e1;
            padding: 6px 8px;
            text-align: left;
        }}
        th {{
            background-color: #f1f5f9;
            color: #334155;
            font-weight: bold;
        }}
    </style>
</head>
<body>
    <div class="header">
        <div class="title">{exam_title}</div>
        <div class="subtitle">Organization: {org} | Advertisement No: {advt} | Report Version: {version}</div>
    </div>

    <div class="disclaimer">
        <strong>IMPORTANT DISCLAIMER:</strong> This report is autonomously generated by GovLens AI from verified sources as of {today_str}. Official notices remain the sole authoritative source. Secondary sources, where used, are explicitly labeled.
    </div>

    <h2>1. Exam Overview</h2>
    <p>{report_data.get('exam_overview', default_fallback)}</p>

    <h2>2. Important Dates</h2>
    <p>{report_data.get('important_dates', default_fallback)}</p>

    <h2>3. Eligibility Criteria</h2>
    <p>{report_data.get('eligibility', default_fallback)}</p>

    <h2>4. Personalized Eligibility Evaluation</h2>
    <p>{report_data.get('personalized_eligibility', default_fallback)}</p>

    <h2>5. Vacancy Details</h2>
    <p>{report_data.get('vacancies', default_fallback)}</p>

    <h2>6. Salary & Pay Scale</h2>
    <p>{report_data.get('salary', default_fallback)}</p>

    <h2>7. Application Fees</h2>
    <p>{report_data.get('application_fees', default_fallback)}</p>

    <h2>8. Required Documents</h2>
    <p>{report_data.get('required_documents', default_fallback)}</p>

    <h2>9. Selection Process</h2>
    <p>{report_data.get('selection_process', default_fallback)}</p>

    <h2>10. Exam Pattern & Syllabus</h2>
    <p>{report_data.get('exam_pattern_syllabus', default_fallback)}</p>

    <h2>11. Application Procedure</h2>
    <p>{report_data.get('application_procedure', default_fallback)}</p>

    <h2>12. Frequently Asked Questions (FAQs)</h2>
    <p>{report_data.get('faqs', default_fallback)}</p>

    <h2>13. Important Notes</h2>
    <p>{report_data.get('important_notes', default_fallback)}</p>

    <h2>14. Source References</h2>
    <p>{report_data.get('sources', default_fallback)}</p>
</body>
</html>"""

    try:
        from weasyprint import HTML
        return HTML(string=html_content).write_pdf()
    except Exception as e:
        logger.warning(f"WeasyPrint library unavailable or missing C dependencies ({e}). Returning raw HTML formatted report.")
        # Fallback to UTF-8 encoded formatted document
        return html_content.encode("utf-8")
